import { StyleSheet } from "react-native";
import { Colors } from "@/constants/Colors";

export const styles = StyleSheet.create({
  pageContainer: {
    minHeight: "100vh",
  },
  backgroundImage: {
    height: "100%",
  },
  container: {
    padding: 16,
  },
  locationText: {
    color: Colors.white,
    fontSize: 32,
    fontWeight: "400",
    textAlign: "center",
    marginTop: 60,
  },
  tempText: {
    color: Colors.white,
    fontSize: 96,
    fontWeight: "100",
    textAlign: "center",
  },
  dateText: {
    color: Colors.white,
    fontSize: 28,
    marginTop: 10,
    textAlign: "center",
  },
  coordinateContainer: {
    display: "flex",
    flexDirection: "row",
    marginTop: 20,
    marginBottom: 20,
  },
  coordinateText: {
    flex: 1,
    textAlign: "center",
    fontSize: 26,
    color: Colors.white,
  },
  borderedContainer: {
    borderWidth: 1,
    borderRadius: 20,
    borderColor: Colors.white,
    marginBottom: 20,
  },
  currentWeatherContainer: {
    display: "flex",
    flexDirection: "row",
    padding: 10,
  },
  currentWeatherImage: {
    height: 120,
    width: 150,
  },
  currentWeatherTextContainer: {
    flex: 1,
  },
  currentWeatherText: {
    marginTop: 10,
    color: Colors.white,
    fontSize: 20,
    textAlign: "center",
  },
  currentWeatherConText: {
    marginTop: 6,
    color: Colors.white,
    fontSize: 36,
    textAlign: "center",
    fontWeight: "500",
  },
  windContainer: {
    display: "flex",
    flexDirection: "row",
    gap: 10,
    justifyContent: "space-between",
  },
  iconTextOneLineContainer: {
    display: "flex",
    flexDirection: "row",
    opacity: 0.4,
  },
  iconTextOneLineText: {
    fontSize: 16,
    marginLeft: 5,
    color: Colors.white,
    fontWeight: "600",
  },
  fadedBackgroundContainer: {
    padding: 14,
    backgroundColor: Colors.fadedBlackBackground,
    borderRadius: 20,
    width: "48%",
    aspectRatio: 1,
  },
  fadedBackgroundContainerFullWidth: {
    padding: 14,
    backgroundColor: Colors.fadedBlackBackground,
    borderRadius: 20,
    width: "100%",
    aspectRatio: 2 / 1,
  },
  windInfoContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  windInfoWrapper: {
    width: "50%",
  },
  windTextContainer: {
    width: "50%",
    paddingLeft: 20,
    marginTop: 10,
  },
  windText: {
    marginTop: 20,
    color: Colors.white,
    fontSize: 18,
  },
  windConText: {
    marginTop: 14,
    color: Colors.white,
    fontSize: 32,
    fontWeight: "500",
  },
  uvIndexNum: {
    fontSize: 40,
    color: Colors.white,
    marginTop: 10,
  },
  uvIndexText: {
    fontSize: 18,
    color: Colors.white,
    marginTop: 10,
  },
  humidText: {
    marginTop: 20,
    color: Colors.white,
    fontSize: 14,
  },
  specificTownText: {
    color: Colors.white,
    textAlign: "center",
    fontSize: 32,
    marginTop: 60,
    marginBottom: 20,
    fontWeight: "500",
  },
  eachTownContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderWidth: 1,
    padding: 10,
    borderRadius: 20,
    borderColor: Colors.white,
    backgroundColor: Colors.fadedBlackBackground,
    alignItems: "center",
    marginBottom: 10,
  },
  eachTownIcon: {
    height: 70,
    width: 90,
  },
  eachTownText: {
    fontSize: 26,
    color: Colors.white,
    fontWeight: "500",
  },
  forecastSelectContainer: {
    marginTop: 20,
    borderColor: Colors.white,
    borderWidth: 1,
    borderRadius: 20,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 24,
    paddingRight: 24,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  forecastSelectIcon: {
    borderWidth: 1,
    borderColor: Colors.black,
    height: 60,
    width: 60,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    opacity: 0.7,
  },
  forecastSelectText: {
    fontSize: 26,
  },
  forecastDisplayContainer: {
    marginTop: 20,
    borderColor: Colors.white,
    borderWidth: 1,
    borderRadius: 20,
    padding: 16,
  },
  forecastDisplayRow: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
});
